### ISSUE TITLE
Example on how to add html-overlay

### ISSUE THREAD

**Issue by tomyitav** [openseadragon/html-overlay#1]
Hi, thanks for this awesome project!
An example of how to properly use this overlay would be helpful.
Cheers,
Tom

**Comment by iangilman** [comment]
Glad you like! As mentioned in the readme, https://github.com/openseadragon/html-overlay/blob/master/demo.html is the example code, which you can see running at https://openseadragon.github.io/html-overlay/demo.html. Do you need additional info beyond that?

**Comment by tomyitav** [comment]
That is great, thank you @iangilman!
